[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:hyperf]
command=php /var/www/bin/hyperf.php start
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/www/runtime/hyperf.log
stderr_logfile=/var/www/runtime/hyperf-error.log